/**
 * Gizlilik Politikası (TR + EN).
 * Plain markdown-benzeri metin; LegalScreen tarafında basit Text ile renderlanır.
 *
 * Bu metnin SON güncellenme tarihi `LAST_UPDATED` üzerinden gösterilir.
 * Mağaza listingi için ayrıca dış URL'e (örn. GitHub Pages) host edilmelidir.
 */

export const PRIVACY_LAST_UPDATED = '2026-05-02';

export const PRIVACY_TR = `# MyFitCraft Gizlilik Politikası

Son güncelleme: ${PRIVACY_LAST_UPDATED}

MyFitCraft ("uygulama") gizliliğinize önem verir. Bu politika, uygulamayı kullanırken hangi verilerin toplandığını, nasıl işlendiğini ve haklarınızı açıklar.

## 1. Toplanan Veriler
- Hesap bilgileri: e-posta adresi, görünen ad, profil fotoğrafı (opsiyonel).
- Profil bilgileri: hedef, deneyim seviyesi, boy, kilo, hedef kilo, dil ve tema tercihi.
- Antrenman verileri: tamamladığınız antrenmanlar, set/tekrar/ağırlık kayıtları, kişisel rekorlar, seçtiğiniz/oluşturduğunuz programlar.
- Vücut ölçümleri: kilo, bel, göğüs, kol gibi girdiğiniz ölçüler ve tarih.
- Cihaz ve teknik bilgiler: oturum yönetimi için Firebase Authentication tarafından üretilen anonim kimlikler. Genel telemetri (uygulama sürümü, platform) hata raporlama için kullanılabilir.

Reklam, konum, kişiler, mikrofon, kamera, sağlık (HealthKit/Google Fit) entegrasyonu **şu an** kullanılmamaktadır.

## 2. Verilerin Kullanım Amacı
- Hesabınızı oluşturmak ve oturumunuzu sürdürmek.
- Antrenman, ölçüm ve istatistiklerinizi cihazınızda ve sunucumuzda saklamak.
- Size kişisel öneriler ve raporlar göstermek (kural-tabanlı, cihaz üzerinde çalışan analiz).
- Hata ayıklama ve uygulamayı iyileştirmek.

## 3. Verilerin Saklanması ve Paylaşımı
- Tüm verileriniz Google Firebase (Cloud Firestore + Firebase Authentication) altyapısında saklanır.
- Her kullanıcı yalnızca kendi verisine erişebilir; Firestore Güvenlik Kuralları sahiplik bazlı erişimi zorunlu kılar.
- Verileriniz reklamcılar dahil **üçüncü taraflara satılmaz veya pazarlama amacıyla paylaşılmaz**.
- Yasal yükümlülükler haricinde verileriniz ihraç edilmez.

## 4. Saklama Süresi
- Hesabınız aktif olduğu sürece verileriniz saklanır.
- Hesabınızı silmek istediğinizde tüm verileriniz makul bir süre içinde kalıcı olarak silinir.
- Hesap silme talebiniz için: aşağıdaki iletişim adresinden bize ulaşabilirsiniz.

## 5. Çocukların Gizliliği
Uygulama 13 yaş altı kullanıcılar için tasarlanmamıştır.

## 6. Reklamlar (İleride)
Şu anda uygulamada reklam yoktur. İleride reklam (örn. AdMob) eklenirse bu politika güncellenecek; reklam ağı tarafından toplanan veriler ayrıca açıklanacaktır. Reklamlı sürüm yayınlandığında, ilk açılışta sizden açık onay (consent) alınacaktır.

## 7. Haklarınız (KVKK / GDPR)
Aşağıdaki haklara sahipsiniz:
- Verilerinize erişme.
- Düzeltme talep etme.
- Silme talep etme ("unutulma hakkı").
- İşlemeyi sınırlandırma veya itiraz etme.
- Veri taşınabilirliği.

Bu hakları kullanmak için aşağıdaki iletişim adresinden bize ulaşabilirsiniz.

## 8. Güvenlik
- Bağlantılar HTTPS üzerinden şifrelidir.
- Şifreniz Firebase tarafından güvenli şekilde hash'lenir; uygulama veya sunucumuz şifrenize doğrudan erişemez.
- Firestore Güvenlik Kuralları sayesinde başka kullanıcıların verisi size kapalıdır.

## 9. Politika Değişiklikleri
Bu politika güncellenebilir. Önemli değişikliklerde uygulama içinde bildirim gösterilir. Son güncelleme tarihi her zaman bu sayfanın üstünde belirtilir.

## 10. İletişim
Soru ve talepleriniz için: myfitcraft.app@gmail.com
`;

export const PRIVACY_EN = `# MyFitCraft Privacy Policy

Last updated: ${PRIVACY_LAST_UPDATED}

MyFitCraft ("the app") respects your privacy. This policy explains what data we collect, how we use it, and your rights.

## 1. Data We Collect
- Account: email, display name, profile photo (optional).
- Profile: goal, experience level, height, weight, target weight, language and theme preference.
- Workouts: completed workouts, set/rep/weight logs, personal records, programs you select or create.
- Body measurements: weight, waist, chest, arm circumference and the date you entered them.
- Device & technical data: anonymous identifiers generated by Firebase Authentication for session management. Basic telemetry (app version, platform) may be used for crash reporting.

We do **not** currently use ads, location, contacts, microphone, camera, or HealthKit/Google Fit integrations.

## 2. How We Use Your Data
- Create your account and keep you signed in.
- Store your workouts, measurements, and statistics on your device and on our backend.
- Show personalized rule-based insights and reports (computed locally on your device).
- Debug and improve the app.

## 3. Storage and Sharing
- All data is stored on Google Firebase (Cloud Firestore + Firebase Authentication).
- Each user can only access their own data; Firestore Security Rules enforce ownership-based access.
- Your data is **not sold or shared with third parties for marketing purposes**, including ad networks.
- We do not export your data except where legally required.

## 4. Retention
- Your data is kept while your account is active.
- When you request account deletion, all of your data will be permanently deleted within a reasonable period.
- For deletion requests, contact us at the address below.

## 5. Children's Privacy
The app is not intended for users under 13.

## 6. Ads (Future)
There are currently no ads in the app. If ads (e.g. AdMob) are added in a future version, this policy will be updated and any data collected by the ad network will be disclosed. You will be asked for explicit consent before any ad is shown.

## 7. Your Rights (GDPR / KVKK)
You have the right to:
- Access your data.
- Request correction.
- Request deletion ("right to be forgotten").
- Restrict or object to processing.
- Data portability.

To exercise these rights, contact us at the address below.

## 8. Security
- All connections are encrypted over HTTPS.
- Your password is hashed by Firebase; neither the app nor our backend can access it directly.
- Firestore Security Rules prevent any user from accessing another user's data.

## 9. Changes to This Policy
This policy may be updated. Significant changes will be announced inside the app. The last-updated date is always shown at the top.

## 10. Contact
For questions or requests: myfitcraft.app@gmail.com
`;
